### ISSUE TITLE
《深入实践Spring Boot》

### ISSUE THREAD

**Issue by huihuidaxia** [huihuidaxia/show_me_the_book#38]
- [x] 第1章 Spring Boot入门
- [x] 第2章 在Spring Boot中使用数据库
- [x] 第3章 Spring Boot界面设计
- [x] 第4章 提高数据库访问性能
- [x] 第5章 Spring Boot安全设计
- [ ] 第6章 Spring Boot SSO
- [ ] 第7章 使用分布式文件系统
- [ ] 第8章 云应用开发
- [ ] 第9章 构建高性能的服务平台
- [ ] 第10章 Spring Boot自动配置实现原理
- [ ] 第11章 Sping Boot数据库访问实现原理
- [ ] 第12章 微服务核心技术实现原理

**Comment by huihuidaxia** [comment]
mongoDB和Neo4j这二种数据库未接触过，暂时略过章节

**Comment by huihuidaxia** [comment]
redis数据库准备使用内嵌的[emmbedded-redis](https://github.com/kstyrc/embedded-redis)，但是整个代码未调试成功，待后面仔细调试 😭

**Comment by huihuidaxia** [comment]
第二章阅读完毕 😆

**Comment by huihuidaxia** [comment]
第3章讲了SpringBoot对MVC的支持，视图采用theymeleaf，章节无亮点，对本人无帮助 😭

**Comment by huihuidaxia** [comment]
Security这一章使用了Cloud-Security，内容有点鸡肋，但是部分内容我并未掌握，可以在看第二遍 👍

**Comment by WilderGao** [comment]
代码清单写不清楚，我看了好难受
